name: Deploy App (Dev & Prod)

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # ========================
      # DEV DEPLOYMENT
      # ========================
      - name: Deploy to Backend DEV
        if: github.ref == 'refs/heads/dev'
        uses: azure/webapps-deploy@v2
        with:
          app-name: whitelabel-poc-be-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND_DEV }}
          package: .

      - name: Deploy to Frontend DEV
        if: github.ref == 'refs/heads/dev'
        uses: azure/webapps-deploy@v2
        with:
          app-name: whitelabel-poc-fe-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND_DEV }}
          package: .

      # ========================
      # PROD DEPLOYMENT
      # ========================
      - name: Deploy to Backend PROD
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: whitelabel-poc-be-prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND_PROD }}
          package: .

      - name: Deploy to Frontend PROD
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: whitelabel-poc-fe-prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND_PROD }}
          package: .
