[server]
port = 8000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""
fileWatcherType = "none"
runOnSave = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = ""
serverPort = 8000

[runner]
fastReruns = false
magicEnabled = true
installTracer = false
fixMatplotlib = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
